name: "Setup and install"
description: "Common setup steps for Actions"
inputs:
  node-version:
    description: "Version of Node.js"
    required: true
    default: "20"

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: pnpm install
