name: "Setup and install"
description: "Common setup steps for Actions"
inputs:
  node-version:
    description: "Version of Node.js"
    required: true
    default: "22"

runs:
  using: composite
  steps:
    - name: Setup corepack
      # --force to overwrite existing yarn binary on Windows (we don't need it anyway)
      run: |
        npm install -g corepack@latest --force
        corepack enable
      shell: bash

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      shell: bash
      run: pnpm install
